services:
  - type: web
    name: nova-ecommerce
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: BASE_URL
        sync: false
      - key: ADMIN_EMAIL
        value: admin@nova.style
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_NAME
        value: Admin
