const sampleProducts = [
  {
    name: 'NOVA Classic Tee',
    description: 'Premium cotton t-shirt with a clean relaxed fit and a soft everyday finish.',
    price: 29.99,
    compareAtPrice: 39.99,
    category: 't-shirts',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1503341504253-dff48f6fbe6e?auto=format&fit=crop&w=1000&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'White'],
    stock: 50,
    featured: true,
    active: true,
  },
  {
    name: 'NOVA Hoodie',
    description: 'Heavyweight fleece hoodie with a relaxed fit, brushed interior, and front pocket.',
    price: 59.99,
    category: 'hoodies',
    images: [
      'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1578681994506-b8f463449011?auto=format&fit=crop&w=1000&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Gray', 'Black'],
    stock: 30,
    featured: true,
    active: true,
  },
  {
    name: 'NOVA Cargo Pants',
    description: 'Relaxed utility pants with a tapered leg, durable fabric, and multiple pockets.',
    price: 69.99,
    category: 'pants',
    images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1000&q=85'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Olive', 'Black'],
    stock: 20,
    active: true,
  },
  {
    name: 'NOVA Cap',
    description: 'Adjustable cotton cap finished with a minimal embroidered NOVA mark.',
    price: 19.99,
    category: 'accessories',
    images: ['https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=1000&q=85'],
    sizes: ['OS'],
    colors: ['Black', 'Cream'],
    stock: 100,
    active: true,
  },
  {
    name: 'NOVA Bomber Jacket',
    description: 'Lightweight bomber jacket with ribbed cuffs and an easy layered silhouette.',
    price: 99.99,
    category: 'outerwear',
    images: ['https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=1000&q=85'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Black'],
    stock: 10,
    featured: true,
    active: true,
  },
  {
    name: 'NOVA Socks (3-pack)',
    description: 'Comfortable crew socks in a versatile three-pack for everyday rotation.',
    price: 12.99,
    category: 'accessories',
    images: ['https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=1000&q=85'],
    sizes: ['OS'],
    colors: ['White'],
    stock: 200,
    active: true,
  },
  {
    name: 'NOVA Oversized Tee',
    description: 'Streetwear oversized tee with dropped shoulders and a structured heavyweight feel.',
    price: 34.99,
    category: 't-shirts',
    images: ['https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=1000&q=85'],
    sizes: ['L', 'XL', 'XXL'],
    colors: ['Charcoal', 'White'],
    stock: 40,
    active: true,
  },
  {
    name: 'NOVA Track Pants',
    description: 'Slim tapered track pants with an elastic waist and movement-friendly fabric.',
    price: 49.99,
    category: 'pants',
    images: ['https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=1000&q=85'],
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'Navy'],
    stock: 25,
    active: true,
  },
  {
    name: 'NOVA Beanie',
    description: 'Warm knitted beanie with a subtle logo tag and a comfortable everyday fit.',
    price: 14.99,
    category: 'accessories',
    images: ['https://images.unsplash.com/photo-1575428652377-a2d80e2277fc?auto=format&fit=crop&w=1000&q=85'],
    sizes: ['OS'],
    colors: ['Black', 'Rust'],
    stock: 80,
    active: true,
  },
  {
    name: 'NOVA Denim Jacket',
    description: 'Classic denim jacket with a modern cut, sturdy texture, and easy layering profile.',
    price: 119.99,
    category: 'outerwear',
    images: ['https://images.unsplash.com/photo-1543076447-215ad9ba6923?auto=format&fit=crop&w=1000&q=85'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Blue'],
    stock: 8,
    active: true,
  },
];

module.exports = sampleProducts;
